name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v2.1.0
      with:
       distribution: 'adopt'
       java-version: '11'
    - name: Build the project
      run: ./gradlew assembleRelease
    - name: Upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: wzieba/Sample-App
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Testers
        file: androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk
        notifyTesters: true
        debug: false
